version: "3"
services:
  server:
    env_file:
      - .env
    build:
      context: .
    image: ghcr.io/skeletonbear/front-end-punmaew:latest
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: punmaew
