version : '3'
services :
  server :
    env_file:
      - .env
    build: 
      context: .
    image: frontend:latest
    ports:
      - "8080:8080"
      
networks:
  default:
    external:
      name: punmaew

