version: "3"
services:
  server:
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env
    build:
      context: .
    image: ghcr.io/skeletonbear/front-end-punmaew:latest
    ports:
      - "8080:443"

networks:
  default:
    external:
      name: punmaew
